# Generated by Django 5.0.3 on 2024-03-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestModel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(max_length=200),
        ),
    ]
