# Generated by Django 5.0.3 on 2024-04-20 21:50

import TestModel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TestModel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    (TestModel.models.Task_status["Not_Started"], "Not started"),
                    (TestModel.models.Task_status["In_Progress"], "In progress"),
                    (TestModel.models.Task_status["Done"], "Done"),
                ],
                default=TestModel.models.Task_status["Not_Started"],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="type",
            field=models.CharField(
                choices=[
                    (TestModel.models.Task_status["Not_Started"], "Not started"),
                    (TestModel.models.Task_status["In_Progress"], "In progress"),
                    (TestModel.models.Task_status["Done"], "Done"),
                ],
                default=TestModel.models.Task_type["Other"],
                max_length=100,
            ),
        ),
    ]
