# Generated by Django 5.0.2 on 2024-03-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_rename_name_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
