# Generated by Django 5.0.3 on 2024-03-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TestModel", "0002_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="name",
            new_name="username",
        ),
    ]
